### ISSUE TITLE
Can run the container

### ISSUE THREAD

**Issue by antoineVerlant** [syncthing/docker#1]
Hey, I just tried this command: 
`sudo docker run -p 8384:8384 -p 22000:22000 --name syncthing -v /var/syncthing/Sync:/var/syncthing/Sync -v /var/syncthing/config:/var/syncthing/config syncthing/syncthing:latest`
and here is the result : 
`15:11:47 WARNING: chmod /var/syncthing/config: operation not permitted

[monitor] 15:11:47 INFO: Starting syncthing
15:11:47 WARNING: chmod /var/syncthing/config: operation not permitted
[start] 15:11:47 INFO: Generating ECDSA key and certificate for syncthing...
[start] 15:11:47 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 15:11:47 INFO: Syncthing exited: exit status 1
[monitor] 15:11:48 INFO: Starting syncthing
15:11:48 WARNING: chmod /var/syncthing/config: operation not permitted
[start] 15:11:48 INFO: Generating ECDSA key and certificate for syncthing...
[start] 15:11:48 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 15:11:48 INFO: Syncthing exited: exit status 1
[monitor] 15:11:49 INFO: Starting syncthing
15:11:49 WARNING: chmod /var/syncthing/config: operation not permitted
[start] 15:11:49 INFO: Generating ECDSA key and certificate for syncthing...
[start] 15:11:49 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 15:11:49 INFO: Syncthing exited: exit status 1
[monitor] 15:11:50 INFO: Starting syncthing
15:11:50 WARNING: chmod /var/syncthing/config: operation not permitted
[start] 15:11:50 INFO: Generating ECDSA key and certificate for syncthing...
[start] 15:11:50 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 15:11:50 INFO: Syncthing exited: exit status 1
[monitor] 15:11:51 WARNING: 4 restarts in 4.244055344s; not retrying further`

**Comment by calmh** [comment]
Your user does not have the appropriate permissions on /var/syncthing/config

**Comment by antoineVerlant** [comment]
Yes I undertstand that but how to select the user while running the container.
I execute docker command as root
Thanks for help

**Comment by calmh** [comment]
Ah, my bad, sorry. The container runs it as uid 1000. That should probably be configurable somewhere.

**Comment by naggie** [comment]
I just hit this issue too, when using a named docker volume instead of mapping on to a path where I can't control the permissions.

Is there a technical reason why the UID/username has to be changed from the default?

Thanks!

**Comment by calmh** [comment]
It may be a misunderstanding from my side. What's the default if not root?

**Comment by naggie** [comment]
Yes, it's effectively root.

**Comment by calmh** [comment]
I think that's a bad default. Syncthing itself will complain as it does not want to be root, and the file ownership will pretty much never be what you want. Uid 1000 might also be wrong for you, but at least it's something that clearly requires changing rather than silently dropping root owned files everywhere.

**Comment by saesh** [comment]
I had the same issue with named volumes. I switched to regular mounted directories which were owned by `1000:1000`.

**Comment by wtigotw** [comment]
I've had the same problem as @saesh. Docker assumes that all work will be done as root. This means that when it sets up a named volume, the volume has permissions of 755 and owned by root:root. This doesn't work with syncthing. I would suggest that it would be appropriate that a command run as root, prior to the startup of syncthing, to chown the /var/syncthing/config directory. This would really help folk like myself that want to use named volumes.

**Comment by calmh** [comment]
That'd work, although I'm not 100% sure if it's the right thing to do. Mind opening a separate issue with that suggestion, for discussion? This one is a bit long in the tooth
