### ISSUE TITLE
Container cannot start

### ISSUE THREAD

**Issue by AndrewSav** [syncthing/docker#11]
I'm not having any joy running it:
```
root@localhost:~# docker run -p 8384:8384 -p 22000:22000 \
>     -v /wherever/st-cfg:/var/syncthing/config \
>     -v /wherever/st-sync:/var/syncthing \
>     syncthing/syncthing:latest
09:55:17 WARNING: chmod /var/syncthing/config/: operation not permitted
[monitor] 09:55:17 INFO: Starting syncthing
09:55:17 WARNING: chmod /var/syncthing/config/: operation not permitted
[start] 09:55:17 INFO: Generating ECDSA key and certificate for syncthing...
[start] 09:55:17 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 09:55:17 INFO: Syncthing exited: exit status 1
[monitor] 09:55:18 INFO: Starting syncthing
09:55:18 WARNING: chmod /var/syncthing/config/: operation not permitted
[start] 09:55:18 INFO: Generating ECDSA key and certificate for syncthing...
[start] 09:55:18 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 09:55:18 INFO: Syncthing exited: exit status 1
[monitor] 09:55:19 INFO: Starting syncthing
09:55:19 WARNING: chmod /var/syncthing/config/: operation not permitted
[start] 09:55:19 INFO: Generating ECDSA key and certificate for syncthing...
[start] 09:55:19 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 09:55:19 INFO: Syncthing exited: exit status 1
[monitor] 09:55:20 INFO: Starting syncthing
09:55:20 WARNING: chmod /var/syncthing/config/: operation not permitted
[start] 09:55:20 INFO: Generating ECDSA key and certificate for syncthing...
[start] 09:55:20 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
[monitor] 09:55:20 INFO: Syncthing exited: exit status 1
[monitor] 09:55:21 WARNING: 4 restarts in 4.220541084s; not retrying further
root@localhost:~#
```
What might be the problem?

**Comment by mr-bolle** [comment]
Hi, 

you have to adjust the Hostpath before you run the Container.
Please create 2 Folder on your Host, and give the docker user the Permission to this one.

> sudo mkdir /mnt/st-cfg && sudo mkdir /mnt/st-sync && sudo chown -R 1000:1000 -R /mnt/st-cfg && chown -R 1000:1000 -R /mnt/st-sync

and run the container with follow command

> docker run -p 8384:8384 -p 22000:22000 \
	-v /mnt/st-cfg:/var/syncthing/config \
	-v /mnt/st-sync:/var/syncthing \
	syncthing/syncthing:latest

**Comment by AndrewSav** [comment]
It might be worth adding to the readme. Btw it's the first image that required me to set permissions for volumes before hand, usually the volumes are created automagically and just work. Do you happen to know, why these special requirements here?

**Comment by mr-bolle** [comment]
This is necessary because of the Docker operation. Each container works in isolation, and if you start a new one, the synchronized data would be lost.

Therefore, it is necessary to transfer the configuration and data directory to the host.

[more Details](https://docs.docker.com/engine/admin/volumes/volumes/)

**Comment by AndrewSav** [comment]
Sorry, that's not what I asked. I have some idea how volumes work and why. What I'm asking is that I was never required to set permissions for them mounted volumes explicitly in any of the plethora of docker images I used before. And I'd like to know why do I have to set explicit permissions with synthing image.

**Comment by mr-bolle** [comment]
I wrote this, however I don't know if you use a other user as root for docker. That you have full access to the files into your host.

If it works with you, you don't need to change it.

**Comment by AndrewSav** [comment]
Still suggest updating the documentation. Cheers.

**Comment by darkadept** [comment]
Had the same problem. I agree with @AndrewSav, I've never had to set permissions on data volumes before either. The docs should definitely reflect this.

**Comment by mr-bolle** [comment]
Hi @darkadept, do you have created both path on your host, before you start the container? Or you only have permission issues?

**Comment by rubenbe** [comment]
Another possibility would be to use user namespaces (aka "the proper solution") to remap file ownership.
Unfortunately docker support is limited and needs specific configuration on the level of docker daemon.

https://docs.docker.com/engine/security/userns-remap/
https://success.docker.com/article/Introduction_to_User_Namespaces_in_Docker_Engine

**Comment by darkadept** [comment]
@mr-bolle: I created both paths first. Just the permission issue.
