### ISSUE TITLE
Provide a way to set a GUI user/password on container creation

### ISSUE THREAD

**Issue by cbenhagen** [syncthing/docker#14]
Currently newly created containers have a world readable GUI without password. What about using an enviroment variable for it? Syncthing once allowed overriding username/password by setting the `STGUIAUTH` to something like "admin:1234". This is obviously very insecure on a desktop machine but could work in a docker container.

**Comment by calmh** [comment]
Docker image is now created by the dockerfile in the main repo, as an auto build by docker hub.

(I would solve this issue by pre-populating a config file, but there may be other ways.)
