### ISSUE TITLE
chmod /var/syncthing/config/: operation not permitted

### ISSUE THREAD

**Issue by hadrien-toma** [syncthing/docker#17]
## Steps to reproduce
Create a `docker-compose.yml` file containing:
```
version: '3.4'

services:
  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    network_mode: "host"
    volumes:
      - config:/var/syncthing/config
      - data:/var/syncthing

volumes:
  config:
  data:
```
Then, running `docker-compose up` in the directory containing the `docker-compose.yml` file gives me:
```
Creating volume "src_data" with default driver
Creating volume "src_config" with default driver
Creating syncthing ... done
Attaching to syncthing
syncthing    | 16:00:39 WARNING: chmod /var/syncthing/config/: operation not permitted
syncthing    | [monitor] 16:00:39 INFO: Starting syncthing
syncthing    | 16:00:39 WARNING: chmod /var/syncthing/config/: operation not permitted
syncthing    | [start] 16:00:39 INFO: Generating ECDSA key and certificate for syncthing...
syncthing    | [start] 16:00:39 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
syncthing    | [monitor] 16:00:39 INFO: Syncthing exited: exit status 1
syncthing    | [monitor] 16:00:40 INFO: Starting syncthing
syncthing    | 16:00:40 WARNING: chmod /var/syncthing/config/: operation not permitted
syncthing    | [start] 16:00:40 INFO: Generating ECDSA key and certificate for syncthing...
syncthing    | [start] 16:00:40 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
syncthing    | [monitor] 16:00:40 INFO: Syncthing exited: exit status 1
syncthing    | [monitor] 16:00:41 INFO: Starting syncthing
syncthing    | 16:00:41 WARNING: chmod /var/syncthing/config/: operation not permitted
syncthing    | [start] 16:00:41 INFO: Generating ECDSA key and certificate for syncthing...
syncthing    | [start] 16:00:41 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
syncthing    | [monitor] 16:00:41 INFO: Syncthing exited: exit status 1
syncthing    | [monitor] 16:00:42 INFO: Starting syncthing
syncthing    | 16:00:42 WARNING: chmod /var/syncthing/config/: operation not permitted
syncthing    | [start] 16:00:42 INFO: Generating ECDSA key and certificate for syncthing...
syncthing    | [start] 16:00:42 FATAL: save cert: open /var/syncthing/config/cert.pem: permission denied
syncthing    | [monitor] 16:00:42 INFO: Syncthing exited: exit status 1
syncthing    | [monitor] 16:00:43 WARNING: 4 restarts in 4.15742737s; not retrying further
syncthing exited with code 1
```

## Question
What am I doing wrong? :disappointed: 

## Environment
- OS: Ubuntu 16.04
- Docker: 18.01.0-ce, build 03596f5
- Docker-compose: 1.18.0, build 8dd22a9

**Comment by mr-bolle** [comment]
Hi, please check follow thread [#11](https://github.com/syncthing/docker/issues/11#issuecomment-342202554) 

Do you use root for docker, or another user?
Docker create the volume shares on your host (config and data) in the current directory. And for this you need write access.  

>    volumes:
>       - config:/var/syncthing/config
>       - data:/var/syncthing
**My recommendation:** 
1. create folder, and set the permission for your current User
`sudo mkdir /mnt/st-cfg && sudo mkdir /mnt/st-sync && sudo chown -R 1000:1000 -R /mnt/st-cfg && chown -R 1000:1000 -R /mnt/st-sync`

2. set this Folder into your docker-compose
>    volumes:
>       - /mnt/st-cfg:/var/syncthing/config
>       - /mnt/st-sync:/var/syncthing

**Comment by rubenbe** [comment]
As @mr-bolle says this is indeed a permissions issue,
In case you don't want to map your volumes to a hardcoded host directory, you can also solve it by running:

`docker-compose up -d ; docker exec -u root syncthing chown 1000:1000 -R /var/syncthing`

**Comment by hadrien-toma** [comment]
@mr-bolle's solution satisfied me very well!
