### ISSUE TITLE
missing arm/armhf version

### ISSUE THREAD

**Issue by testbird** [syncthing/docker#19]
Got "exec format error", looked, but could not find any version for arm based boards, am I overlooking something?

**Comment by testbird** [comment]
Well, this unofficial build code may help you provide official images https://github.com/linuxserver/docker-syncthing-armhf

**Comment by reijin90** [comment]
or you can replace all "amd64" strings with "arm" or "arm64" inside the Dockerfile

**Comment by calmh** [comment]
Docket image is now created by the dockerfile in the main repo, as an auto build by docker hub
