### ISSUE TITLE
Please update image to v0.14.35

### ISSUE THREAD

**Issue by smarrk** [syncthing/docker#2]
Emergency update v0.14.35 has been released today.  
The image "still" provides the vulnerable v0.14.34.

Please update the `Dockerfile` to the latest version - thanks ;-)

**Comment by calmh** [comment]
Done!

**Comment by smarrk** [comment]
Thanks!

Is there a reason that the version is hard coded in the Dockerfile? It seems a lot easier to me (from an organizational view) to automatically get the latest version.

Are you interested in a Pull Request introducing the above behaviour?

**Comment by calmh** [comment]
Sure. Although that may not be as trivial as it seems, and we anyway need to trigger rebuild of the container somehow.

**Comment by naggie** [comment]
I think that wouldn't be idiomatic docker, we'd lose the immutability of containers. In theory, so long as the config and data is mapped out and can be understood by the new version of syncthing ,the container can simply be replaced with the new version.

Perhaps making the described method more automatic is a better solution, unless I'm missing something.

**Comment by smarrk** [comment]
Maybe that was blurry: I'm not talking about getting the newest version when starting the container, but when building the image.

I was thinking about something like this in the `Dockerfile`:

```
...
RUN mkdir /syncthing \
    && cd /syncthing \
    && release=$(curl -s https://api.github.com/repos/syncthing/syncthing/releases/latest | awk '/\/syncthing-linux-amd64/ {print $2}' | xargs dirname | xargs basename) \
    && curl -s -L https://github.com/syncthing/syncthing/releases/download/${release}/syncthing-linux-amd64-${release}.tar.gz \
...
```

This gets the latest release via GitHub-API and extracts the version number, instead of using the fixed `ENV` variable.

**Comment by naggie** [comment]
Ah, I see what you mean. Yes it would make sense to default to the latest release. For some reason I read `Dockerfile` and thought container.
