### ISSUE TITLE
No versioned images since v0.14.32

### ISSUE THREAD

**Issue by rubenbe** [syncthing/docker#4]
Hi

Unfortunately, since v0.14.32 new versions are no longer tagged as new releases.
As a consequence, all new builds are marked as "latest" on docker hub [0]

It would be awesome if releases would be tagged again.
As such a specific syncthing version can be installed using docker.

Thanks!

[0] https://hub.docker.com/r/syncthing/syncthing/builds/

**Comment by calmh** [comment]
I don't think we can reliably do this since #3.

**Comment by smarrk** [comment]
+1 for re-enabling versioned build.

May I ask how you did this before #3?

**Comment by calmh** [comment]
I just tagged the commit in the repo that changed the dockerfile to download the corresponding Syncthing release.

**Comment by smarrk** [comment]
I'm not familiar with docker hub, but as far as I can see you can [trigger automated builds by commit tags](https://docs.docker.com/docker-hub/builds/#use-the-build-settings-page).  
I may be wrong but this seems to be an option to build one image tagged with `latest` and another one tagged with the latest commit tag.

**Comment by calmh** [comment]
Yes, but since the dockerfile always grabs the latest version there is no guaranteed correlation. We'll end up with lots and lots of tags on the same commit in the repo, and accidentally pushing an old tag for whatever reason would end up with a build tagged like that but with whatever the latest version is instead.

**Comment by smarrk** [comment]
Ah, ok, now I see the problem (I assumed docker hub would always build the highest/latest commit tag regardless what have been pushed).

I agree, that this isn't reliable. Maybe #3 needs to be reverted :-(

**Comment by rubenbe** [comment]
Another possibility is to adapt the new-release script to create a branch, set the version and tag it.
Then in the docker hub correct hooks.

As such, new "dockerfile features" are automatically taken along in the versioned images.
I'll make a pull request with a proposal, give me some time ;)

**Comment by calmh** [comment]
I think that would be fine. If the branch is named `v1.2.3` like the release Docker hub will tag the container appropriately without us needing an actual git tag as well.

**Comment by rubenbe** [comment]
The tagging is indeed, strictly seen not needed.
The reason I did not choose a "release" branch is to automatically include changes from the master, without needing a manual branch/cherry pick
