### ISSUE TITLE
Docker volumes Parameter don't use as Folder Path (tilde character)

### ISSUE THREAD

**Issue by mr-bolle** [syncthing/docker#8]
Hi, 

i run the Docker Container with follow volumes parameter. 

`docker run -p 8384:8384 -p 22000:22000 -v /mnt/syncthing_config:/var/syncthing/config -v /mnt/syncthing_data:/var/syncthing/Sync syncthing/syncthing:latest `

![15-09-_2017_21-16-58](https://user-images.githubusercontent.com/22414212/30499565-4d1d6d30-9a5b-11e7-9368-ed7fdd1b95bf.jpg)

If i use the tilde character (~) and add the Foldername, i can not find the synchronized folder on the host.
I must add the unterpath "Sync" after the tilde and additional ex. Folder Label.

Is there a way that the default path specified for the docker container is used as Folder Path?

**A fast solution would be change the path to into 
["Example usage:"](https://github.com/syncthing/docker/blob/master/README.md) to "-v /wherever/st-sync:/var/syncthing"** 

best regards
Raiko

**Comment by calmh** [comment]
Indeed, the suggested example config is for the `default` folder. For other folders it would make sense to map them as separate volumes. Probably this could be clearer. 

And we might benefit from a way to set the uid Syncthing runs as at start time.

**Comment by mr-bolle** [comment]
Hi @calmh, 

i don't thing it is necessarry to create a customize default folder during Container start. If you can give me write Access i will change the README.me and we have to use the default folder from the Dockerfile.

br Raiko

**Comment by rubenbe** [comment]
@mr-bolle can you make a pull request with your suggested change? Thanks!

**Comment by mr-bolle** [comment]
Hi @rubenbe, today I learned by a other project, how github.com pull requests works ;)
Tomorrow I will do this changes into syncthing.

**Comment by rubenbe** [comment]
Merged!
